# Site settings
title: Ashish Sharma
email: ashshar@cs.washington.edu
description: > # this means to ignore newlines until "baseurl:"
   Computer Science PhD Student at the University of Washington.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ash-shar.github.io/" # the base hostname & protocol for your site
production_url: "https://ash-shar.github.io/"
github_username: ash-shar
permalink: /blog/:year/:month/:title.html

twitter:
  username: sharma_ashish_2

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
