# Site settings
title: Hongbin Na
email: hongbin.na@student.uts.edu.au
description: > # this means to ignore newlines until "baseurl:"
   Master of Research student at the University of Technology Sydney.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hongbin-ze.github.io/" # the base hostname & protocol for your site
production_url: "https://hongbin-ze.github.io/"
github_username: hongbin-ze
permalink: /blog/:year/:month/:title.html

twitter:
  username: HongbinNLP

sass:
  style: compressed

collections:
  publications:
    output: true

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
