- position: "Organizer"
  at: BioNLP 2026 Shared Task
- position: "Reviewer"
  at: ICLR 2025, ACL 2025, EMNLP 2025, AACL 2025, Psychiatry Research
# - position: "Volunteer"
#   at: PLO 2019, COMSNETS 2017