- position: "Organizer"
  at: Human-Centered Large Language Modeling Workshop at ACL 2024
- position: "PC/Reviewer"
  at: ACL 2023, ICWSM 2023, CHI 2023, ACL 2022, ARR 2022, EMNLP 2022, NAACL 2022, WWW 2022, ICWSM 2022, CHI 2022, KDD 2022, W-NUT 2022, ACL 2021, EMNLP 2021, WWW 2021, ICWSM 2021, MAISoN 2021, W-NUT 2021, ACL 2020, EMNLP 2020, TCSS 2020, NAACL 2019, PAKDD 2019
- position: "Volunteer"
  at: PLO 2019, COMSNETS 2017