- position: "Organizer"
  at: PsyDefDetect Shared Task BioNLP@ACL 2026
- position: "Reviewer"
  at: ICLR 2025-2026, ACL ARR 2025-2026, Psychiatry Research
# - position: "Volunteer"
#   at: PLO 2019, COMSNETS 2017